### ISSUE TITLE
[SUGGESTION] Animania support

### ISSUE THREAD

**Issue by Sunconure11** [NightKosh/Sophisticated-wolves#58]
Animania's alterations to most mobs are not supported by this mod, basically making pet carriers useless.

**Comment by NightKosh** [comment]
Hello. I guess it will be better to ask "Animania" developer for support instead of me.
Current version of an API of the Sophisticated wolves mod allows to use pet carriers for any other mobs.

API : https://github.com/NightKosh/Sophisticated-wolves-API/blob/master/sophisticated_wolves/api/pet_carrier/PetCarrier.java

Example(cat) : https://github.com/NightKosh/Sophisticated-wolves/blob/master/src/main/java/sophisticated_wolves/item/pet_carrier/CatPetCarrier.java
Example(chicken) : https://github.com/NightKosh/Sophisticated-wolves/blob/master/src/main/java/sophisticated_wolves/item/pet_carrier/ChickenPetCarrier.java

**Comment by NightKosh** [comment]
It looks like there is a bug with non tameable animals. https://github.com/NightKosh/Sophisticated-wolves/issues/69 
It will be fixed in next release.
